#!/bin/sh

if [ "$#" != "1" ] ; then
	CPUS=2
	MEM=256
else
	CPUS=$1
	MEM=256
fi

if [ "$#" != '2' ]; then
	CPUS=2
	MEM=256
else
	CPUS=$1
	MEM=$2
fi

qemu-system-i386 -serial mon:stdio -hda fs.img -smp $CPUS -m $MEM \
					-d cpu_reset -s -S


